"use strict";

//var kickOffLocation;
var kickOffLocation;
var activityOneLocation;
var activityTwoLocation;

// START SCRIPTING FOR KICKOFF

function kickOffFormChanged() {
    kickOffLocation = document.getElementById("kickOffLocation").value;
    console.log(kickOffLocation);
}

// END SCRIPTING FOR KICKOFF

// START SCRIPTING FOR ACTIVITY ONE PAGE

function ActivityOneLocationChanged(){
    activityOneLocation = document.getElementById("ActivityOneLocation").value;
}


// END SCRIPTING FOR ACTIVITY ONE PAGE

// START SCRIPTING FOR ACTIVITY TWO PAGE

function ActivityTwoLocationChanged(){
    activityTwoLocation = document.getElementById("ActivityTwoLocation").value;
}


// END SCRIPTING FOR ACTIVITY TWO PAGE

// START SCRIPTING FOR PUZZLE ONE




// END SCRIPTING FOR PUZZLE ONE

// START SCRIPTING FOR PUZZLE TWO




// END SCRIPTING FOR PUZZLE TWO

// START SCRIPTING FOR PUZZLE THREE




// END SCRIPTING FOR PUZZLE THREE

// START SCRIPTING FOR PUZZLE FOUR




// END SCRIPTING FOR PUZZLE FOUR

// START SCRIPTING FOR PUZZLE FIVE




// END SCRIPTING FOR PUZZLE FIVE

// START SCRIPTING FOR PUZZLE SIX



// END SCRIPTING FOR PUZZLE SIX

// START SCRIPTING FOR PUZZLE SEVEN




// END SCRIPTING FOR PUZZLE SEVEN

// START SCRIPTING FOR PUZZLE EIGHT




// END SCRIPTING FOR PUZZLE EIGHT

// START SCRIPTING FOR CONGRATULATIONS PAGE




// END SCRIPTING FOR CONGRATULATIONS PAGE

